### ISSUE TITLE
OHLCV scraper

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/danaides#28]
initially
- [ ] ergopad
- [ ] paideia
- [ ] other ergopad IDOs
- [ ] ??

based off older code, store in tables with format:
- ohlcv_[token]_[granularity]
- consider organizing as partitions (postgres)
- granularity should follow cleanup patterns (i.e. 1m for 3 days, 5 mins for 15 days, 1 hour for 3 weeks, 1 week for 3 months)...consider allowing this to be configurable

**Comment by noob77777** [comment]
Same as: https://github.com/ergo-pad/ergopad-api/issues/586?
